version: "3.9"

# ─── Base configuration (re‑used via YAML anchor) ────────────────────────────────
x-base-config: &base-config
  ports:
    - "11235:11235"
    - "7000:7000"
    - "9222:9222"
    - "8080:8080"
  environment:
    - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN:-}
    - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    - CLAUDE_API_KEY=${CLAUDE_API_KEY:-}
  volumes:
    - /dev/shm:/dev/shm
  deploy:
    resources:
      limits:
        memory: 4G
      reservations:
        memory: 1G
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s

# ─── Single service, no profiles ─────────────────────────────────────────────────
services:
  crawl4ai:
    <<: *base-config
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
        INSTALL_TYPE: ${INSTALL_TYPE:-basic}
        ENABLE_GPU: false
      platforms:
        - linux/amd64
